package vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

import controlador.Coordinador;

/**
 *
 * @author Sergio Chica
 */
public class VentanaPrincipal extends JFrame implements ActionListener{

    private javax.swing.JButton botonConsultar;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelTitulo;
    
    private JMenuBar barraMenu;
    private JMenu menu;
    private JMenuItem itemOpciones;
    
    
	private Coordinador miCoordinador;
    
//    private Dimesion tamPantalla;
//    private Rectangle pantalla;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setTitle("Ventana Principal");
        setSize(700,450);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        botonConsultar = new javax.swing.JButton();
        botonRegistrar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(147, 112, 219));
        jPanel1.setLayout(null);

        labelTitulo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Bienvenido al sistema");
        jPanel1.add(labelTitulo);
        labelTitulo.setBounds(37, 25, 213, 80);

        botonConsultar.setText("CONSULTAR");
        jPanel1.add(botonConsultar);
        botonConsultar.addActionListener(this);
        botonConsultar.setBounds(190, 112, 124, 46);

        botonRegistrar.setText("REGISTRAR");
        jPanel1.add(botonRegistrar);
        botonRegistrar.addActionListener(this);
        botonRegistrar.setBounds(37, 112, 124, 46);
        
        barraMenu = new JMenuBar();
        menu = new JMenu();
        itemOpciones = new JMenuItem();
        
        menu.setText("Opciones");
        itemOpciones.setText("Cambiar de usuario");
        itemOpciones.addActionListener(this);
        
        menu.add(itemOpciones);
        barraMenu.add(menu);
        
        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>    

	public void setCoordinador(Coordinador miCoordinador) {
		// TODO Auto-generated method stub
		this.miCoordinador=miCoordinador;
	}

	public void asignarUsuario(String usuario) {
		// TODO Auto-generated method stub
		labelTitulo.setText("Bienvenido: "+ usuario);
		
		if (usuario.equals("Administrador")) {
			botonConsultar.setVisible(true);
			botonRegistrar.setVisible(true);
		}else {
			botonConsultar.setVisible(false);
			botonRegistrar.setVisible(true);
		}
	}

	@Override
	public void actionPerformed(ActionEvent e) {
		// TODO Auto-generated method stub
		if (e.getSource()==itemOpciones) {
			miCoordinador.mostrarLogin();
		}
		
		if (e.getSource()==botonRegistrar) {
			miCoordinador.mostrarRegitro();
		}
		
		if (e.getSource()==botonConsultar) {
			miCoordinador.mostrarConsultar();
		}
	}


}
