package vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

import controlador.Coordinador;
import modelo.vo.UsuarioVO;

/**
 *
 * @author Sergio Chica
 */
public class VentanaConsultar extends JDialog implements ActionListener{

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel;
    private javax.swing.JLabel LabelDescripcion;
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JTextField campoConsultar;
    private javax.swing.JTextField campoDireccion;
    private javax.swing.JTextField campoDocumento;
    private javax.swing.JTextField campoEdad;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoProfesion;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelDocumento;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelProfesion;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
	private Coordinador miCoordinador;
    // End of variables declaration//GEN-END:variables
    /**
     * Creates new form VentanaRegistro
     */
    public VentanaConsultar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Consultar");
        setSize(600, 370);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        JPanel = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        separador1 = new javax.swing.JSeparator();
        LabelDescripcion = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoProfesion = new javax.swing.JTextField();
        labelProfesion = new javax.swing.JLabel();
        campoDireccion = new javax.swing.JTextField();
        labelDireccion = new javax.swing.JLabel();
        labelDocumento = new javax.swing.JLabel();
        campoDocumento = new javax.swing.JTextField();
        labelEdad = new javax.swing.JLabel();
        campoEdad = new javax.swing.JTextField();
        labelTelefono = new javax.swing.JLabel();
        campoTelefono = new javax.swing.JTextField();
        botonCancelar = new javax.swing.JButton();
        separador2 = new javax.swing.JSeparator();
        campoConsultar = new javax.swing.JTextField();
        botonActualizar = new javax.swing.JButton();
        botonBuscar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        JPanel.setBackground(new java.awt.Color(255, 255, 255));
        JPanel.setLayout(null);

        labelTitulo.setBackground(new java.awt.Color(204, 204, 204));
        labelTitulo.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Consultar Usuario");
        JPanel.add(labelTitulo);
        labelTitulo.setBounds(33, 10, 519, 50);

        separador1.setBackground(new java.awt.Color(0, 0, 0));
        separador1.setForeground(new java.awt.Color(102, 102, 102));
        JPanel.add(separador1);
        separador1.setBounds(22, 115, 538, 3);

        LabelDescripcion.setText("Ingrese el documento del usuario a consultar");
        JPanel.add(LabelDescripcion);
        LabelDescripcion.setBounds(33, 78, 247, 16);

        labelNombre.setText("Nombre:");
        JPanel.add(labelNombre);
        labelNombre.setBounds(27, 147, 61, 16);

        JPanel.add(campoNombre);
        campoNombre.setBounds(94, 144, 195, 22);

        JPanel.add(campoProfesion);
        campoProfesion.setBounds(94, 184, 195, 22);

        labelProfesion.setText("Profesion:");
        JPanel.add(labelProfesion);
        labelProfesion.setBounds(27, 187, 53, 16);

        JPanel.add(campoDireccion);
        campoDireccion.setBounds(86, 224, 195, 22);

        labelDireccion.setText("Direccion:");
        JPanel.add(labelDireccion);
        labelDireccion.setBounds(27, 227, 53, 16);

        labelDocumento.setText("Documento:");
        JPanel.add(labelDocumento);
        labelDocumento.setBounds(307, 147, 66, 16);

        JPanel.add(campoDocumento);
        campoDocumento.setBounds(379, 144, 181, 22);
        campoDocumento.setEditable(false);

        labelEdad.setText("Edad: ");
        JPanel.add(labelEdad);
        labelEdad.setBounds(341, 187, 32, 16);

        JPanel.add(campoEdad);
        campoEdad.setBounds(379, 184, 181, 22);

        labelTelefono.setText("Telefono: ");
        JPanel.add(labelTelefono);
        labelTelefono.setBounds(321, 227, 52, 16);


        JPanel.add(campoTelefono);
        campoTelefono.setBounds(379, 224, 181, 22);

        botonCancelar.setText("Cancelar");
        JPanel.add(botonCancelar);
        botonCancelar.setBounds(470, 280, 88, 23);
        botonCancelar.addActionListener(this);

        separador2.setBackground(new java.awt.Color(0, 0, 0));
        separador2.setForeground(new java.awt.Color(102, 102, 102));
        JPanel.add(separador2);
        separador2.setBounds(27, 264, 533, 3);

        JPanel.add(campoConsultar);
        campoConsultar.setBounds(286, 78, 117, 16);

        botonActualizar.setText("Actualizar");
        JPanel.add(botonActualizar);
        botonActualizar.setBounds(270, 280, 88, 23);
        botonActualizar.addActionListener(this);

        botonBuscar.setText("Buscar");
        JPanel.add(botonBuscar);
        botonBuscar.setBounds(415, 78, 97, 25);
        botonBuscar.addActionListener(this);

        botonEliminar.setText("Eliminar");
        JPanel.add(botonEliminar);
        botonEliminar.setBounds(370, 280, 88, 23);
        botonEliminar.addActionListener(this);

        getContentPane().add(JPanel);
        JPanel.setBounds(0, 0, 591, 328);

        pack();
    }// </editor-fold>                        

	public void setCoordinador(Coordinador miCoordinador) {
		// TODO Auto-generated method stub
		this.miCoordinador=miCoordinador;
	}

	@Override
	public void actionPerformed(ActionEvent e) {
		// TODO Auto-generated method stub
		if (e.getSource()==botonBuscar) {
			consultar();
		}
		
		if (e.getSource()==botonActualizar) {
			actualizarUsurio();
		}
		
		if (e.getSource()==botonEliminar) {
			eliminarUsuario();
		}
		
		if (e.getSource()==botonCancelar) {
			limpiarVentana();
			dispose();
		}
	}

	private void eliminarUsuario() {
		// TODO Auto-generated method stub
		String documento=campoDocumento.getText().trim();
		String elimina="";
		
		if (!documento.equals("")) {
			elimina=miCoordinador.eliminarUsuario(documento);
			
			if (elimina.equals("ok")) {
				JOptionPane.showMessageDialog(null, "Se ha eliminado "+ "Correctamente","informacion",JOptionPane.INFORMATION_MESSAGE);
				limpiarVentana();
			}else {
				JOptionPane.showMessageDialog(null, "No se pudo eliminar", "Información",JOptionPane.WARNING_MESSAGE);
			}
		
		}else {
			JOptionPane.showMessageDialog(null, "Ingrese un documento","Informacion",JOptionPane.WARNING_MESSAGE);
		}
		
		
	}

	private void actualizarUsurio() {
		// TODO Auto-generated method stub
		Integer edad=miCoordinador.validarEdad(campoEdad.getText().trim());
		
		if (edad!=null) {
			UsuarioVO miUsuarioVO= new UsuarioVO();
			miUsuarioVO.setDocumento(campoDocumento.getText().trim());
			miUsuarioVO.setNombre(campoNombre.getText().trim());
			miUsuarioVO.setEdad(edad);
			miUsuarioVO.setProfesion(campoProfesion.getText().trim());
			miUsuarioVO.setDireccion(campoDireccion.getText().trim());
			miUsuarioVO.setTelefono(campoTelefono.getText().trim());
			
			String actualiza="";
			
			if (miCoordinador.validarCampos(miUsuarioVO)) {
				actualiza =miCoordinador.actualizarUsuario(miUsuarioVO);			
			}else {
				actualiza="mas_datos";
			}
		
			
			if (actualiza.equals("ok")) {
				JOptionPane.showMessageDialog(null, "Se ha modificado correctamente!!!");
			}else {
				if (actualiza.equals("mas_datos")) {				
					JOptionPane.showMessageDialog(null, "Debe ingresar los campos obligatorios","Faltan Datos",JOptionPane.WARNING_MESSAGE);
				}else {
					JOptionPane.showMessageDialog(null, "Se necesita diligenciar los campos obligatorios(*) !!!","Advertencia",JOptionPane.WARNING_MESSAGE); 				
				}
			}
		}else {
			JOptionPane.showMessageDialog(null, "Debe ingresar una edad Valida!!!","Advertencia",JOptionPane.ERROR_MESSAGE); 							
		}
	}

	private void limpiarVentana() {
		// TODO Auto-generated method stub
		campoConsultar.setText("");
		campoDocumento.setText("");
		campoNombre.setText("");
		campoDireccion.setText("");
		campoEdad.setText("");
		campoProfesion.setText("");
		campoTelefono.setText("");
	}

	private void consultar() {
		// TODO Auto-generated method stub
		UsuarioVO usuarioVO=miCoordinador.consultarUsuario(campoConsultar.getText().trim());
		
		if (usuarioVO!=null) {
			
			campoNombre.setText(usuarioVO.getNombre());
			campoDocumento.setText(usuarioVO.getDocumento());
			campoProfesion.setText(usuarioVO.getProfesion());
			campoEdad.setText(usuarioVO.getEdad()+"");
			campoDireccion.setText(usuarioVO.getDireccion());
			campoTelefono.setText(usuarioVO.getTelefono());
			
		}else {
			JOptionPane.showMessageDialog(null, "El usuario no se encuentra registrado en el sistema");
		}
	}

}
