package vista;

import java.awt.event.ActionEvent;

import java.awt.event.ActionListener;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

import controlador.Coordinador;

import modelo.vo.UsuarioVO;

/**
 *
 * @author Sergio Chica
 */
public class VentanaRegistro extends JDialog implements ActionListener{

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel;
    private javax.swing.JLabel LabelDescripcion;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JTextField campoDireccion;
    private javax.swing.JTextField campoDocumento;
    private javax.swing.JTextField campoEdad;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoProfesion;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelDocumento;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelProfesion;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
	private Coordinador miCoordinador;
    // End of variables declaration//GEN-END:variables
    /**
     * Creates new form VentanaRegistro
     */
    public VentanaRegistro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Registro");
        setSize(600, 370);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        JPanel = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        separador1 = new javax.swing.JSeparator();
        LabelDescripcion = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoProfesion = new javax.swing.JTextField();
        labelProfesion = new javax.swing.JLabel();
        campoDireccion = new javax.swing.JTextField();
        labelDireccion = new javax.swing.JLabel();
        labelDocumento = new javax.swing.JLabel();
        campoDocumento = new javax.swing.JTextField();
        labelEdad = new javax.swing.JLabel();
        campoEdad = new javax.swing.JTextField();
        labelTelefono = new javax.swing.JLabel();
        campoTelefono = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        separador2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JPanel.setBackground(new java.awt.Color(255, 255, 255));
        JPanel.setLayout(null);

        labelTitulo.setBackground(new java.awt.Color(204, 204, 204));
        labelTitulo.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Registro de Usuario");
        labelTitulo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JPanel.add(labelTitulo);
        labelTitulo.setBounds(33, 10, 519, 50);

        separador1.setBackground(new java.awt.Color(0, 0, 0));
        separador1.setForeground(new java.awt.Color(102, 102, 102));
        JPanel.add(separador1);
        separador1.setBounds(22, 100, 533, 3);

        LabelDescripcion.setText("Diligencie el Formulario para registrar el Usuario en el Sistema");
        JPanel.add(LabelDescripcion);
        LabelDescripcion.setBounds(33, 78, 500, 16);

        labelNombre.setText("* Nombre:");
        JPanel.add(labelNombre);
        labelNombre.setBounds(27, 132, 56, 16);


        JPanel.add(campoNombre);
        campoNombre.setBounds(89, 129, 195, 22);


        JPanel.add(campoProfesion);
        campoProfesion.setBounds(89, 169, 195, 22);

        labelProfesion.setText("Profesion:");
        JPanel.add(labelProfesion);
        labelProfesion.setBounds(27, 172, 53, 16);


        JPanel.add(campoDireccion);
        campoDireccion.setBounds(86, 209, 195, 22);

        labelDireccion.setText("Direccion:");
        JPanel.add(labelDireccion);
        labelDireccion.setBounds(27, 212, 53, 16);

        labelDocumento.setText("* Documento:");
        JPanel.add(labelDocumento);
        labelDocumento.setBounds(302, 132, 66, 16);


        JPanel.add(campoDocumento);
        campoDocumento.setBounds(374, 129, 181, 22);

        labelEdad.setText("Edad: ");
        JPanel.add(labelEdad);
        labelEdad.setBounds(336, 172, 32, 16);


        JPanel.add(campoEdad);
        campoEdad.setBounds(374, 169, 181, 22);

        labelTelefono.setText("Telefono: ");
        JPanel.add(labelTelefono);
        labelTelefono.setBounds(316, 212, 52, 16);


        JPanel.add(campoTelefono);
        campoTelefono.setBounds(374, 209, 181, 22);

        botonAceptar.setText("Aceptar");
        JPanel.add(botonAceptar);
        botonAceptar.setBounds(341, 258, 91, 23);
        botonAceptar.addActionListener(this);

        botonCancelar.setText("Cancelar");
        JPanel.add(botonCancelar);
        botonCancelar.setBounds(467, 258, 88, 23);
        botonCancelar.addActionListener(this);

        separador2.setBackground(new java.awt.Color(0, 0, 0));
        separador2.setForeground(new java.awt.Color(102, 102, 102));
        JPanel.add(separador2);
        separador2.setBounds(22, 237, 533, 3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>      

	public void setCoordinador(Coordinador miCoordinador) {
		// TODO Auto-generated method stub
		this.miCoordinador=miCoordinador;
	}

	@Override
	public void actionPerformed(ActionEvent e) {
		// TODO Auto-generated method stub
		if (e.getSource()==botonAceptar) {
			registrar();
		}
		if (e.getSource()==botonCancelar) {
			dispose();
		}
	}

	private void registrar() {
		// TODO Auto-generated method stub
	
		Integer edad=miCoordinador.validarEdad(campoEdad.getText().trim());
		
		if (edad!=null) {
			UsuarioVO miUsuarioVO= new UsuarioVO();
			miUsuarioVO.setDocumento(campoDocumento.getText().trim());
			miUsuarioVO.setNombre(campoNombre.getText());
			miUsuarioVO.setEdad(edad);
			miUsuarioVO.setProfesion(campoProfesion.getText());
			miUsuarioVO.setDireccion(campoDireccion.getText());
			miUsuarioVO.setTelefono(campoTelefono.getText());
			
			String retorno="";
			
			if (miCoordinador.validarCampos(miUsuarioVO)) {
				retorno =miCoordinador.registrarUsuario(miUsuarioVO);			
			}else {
				retorno="mas_datos";
			}
		
			
			if (retorno.equals("ok")) {
				JOptionPane.showMessageDialog(null, "El usuario fue registraddo con exito!!!");
				limpiarVentana();
			}else {
				if (retorno.equals("error")) {				
					JOptionPane.showMessageDialog(null, "El usuario no pudo ser registrado verifique la traza del error!!!");
				}else {
					JOptionPane.showMessageDialog(null, "Se necesita diligenciar los campos obligatorios(*) !!!","Advertencia",JOptionPane.WARNING_MESSAGE); 				
				}
			}
		}else {
			JOptionPane.showMessageDialog(null, "Debe ingresar una edad Valida!!!","Advertencia",JOptionPane.ERROR_MESSAGE); 							
		}
		
	}
	
	private void limpiarVentana() {
		// TODO Auto-generated method stub
		campoDocumento.setText("");
		campoNombre.setText("");
		campoDireccion.setText("");
		campoEdad.setText("");
		campoProfesion.setText("");
		campoTelefono.setText("");
	}

}
