package vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

import controlador.Coordinador;

/**
 *
 * @author Sergio Chica
 */
public class VentanaLogin extends JDialog implements ActionListener{

    private static final long serialVersionUID = 1L;
	// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JPasswordField campoPass;
    private javax.swing.JComboBox<String> comboUsuario;
    private javax.swing.JLabel labelPass;
    private javax.swing.JLabel labelUser;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JLabel tituloLogin;
    
	private Coordinador miCoordinador;
	
    /**
     * Creates new form VentanaLogin
     */
    public VentanaLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Login");
        setSize(264, 340);
        setLocationRelativeTo(null);
        setResizable(false);
        
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        
        addWindowListener(new WindowAdapter() {
        	
        	@Override
        	public void windowClosing(WindowEvent e) {
        		Object[] options= {"Continuar","Cerrar"};
        		int n =JOptionPane.showOptionDialog(null, "Seleccione un tipo de Usuario.\nSi sale el sistema se Cerrara", "Confirmacion",
        				JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
        		if (n == JOptionPane.YES_OPTION) {}
        		else if (n == JOptionPane.NO_OPTION) {
					System.exit(0);//Cerrar todo el sistema
				}
        	}
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        tituloLogin = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        labelPass = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JButton();
        comboUsuario = new javax.swing.JComboBox<>();
        campoPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelLogin.setBackground(new java.awt.Color(153, 153, 153));
        panelLogin.setPreferredSize(new java.awt.Dimension(254, 300));
        panelLogin.setLayout(null);

        tituloLogin.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        tituloLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLogin.setText("Ventana Login");
        panelLogin.add(tituloLogin);
        tituloLogin.setBounds(17, 6, 220, 58);

        labelUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelUser.setText("Usuario");
        panelLogin.add(labelUser);
        labelUser.setBounds(17, 94, 47, 24);

        labelPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelPass.setText("Pass");
        panelLogin.add(labelPass);
        labelPass.setBounds(17, 137, 27, 20);
        labelPass.setVisible(false);

        botonAceptar.setText("Aceptar");
        botonAceptar.setToolTipText("");
        panelLogin.add(botonAceptar);
        botonAceptar.setBounds(150, 261, 87, 23);
        botonAceptar.addActionListener(this);

        comboUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Administrador", "Usuario"}));
        panelLogin.add(comboUsuario);
        comboUsuario.setBounds(70, 95, 167, 24);
        comboUsuario.addActionListener(this);
        
        panelLogin.add(campoPass);
        campoPass.setBounds(70, 137, 167, 22);
        campoPass.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }
 
    /////////////////////////////////////////////////////
    // End of variables declaration//GEN-END:variables
    
	public void setCoordinador(Coordinador miCoordinador) {
		this.miCoordinador=miCoordinador;
	}
	
	@Override
	public void actionPerformed(ActionEvent e) {
		if (e.getSource()==comboUsuario) {
			mostrarElementos();
		}
		if (e.getSource()==botonAceptar) {
			String respuesta=miCoordinador.validarIngreso(comboUsuario.getSelectedIndex(),campoPass.getText());
			
			if (respuesta.equals("error")) {
				JOptionPane.showMessageDialog(null, "No ha seleccionado un usuario");
			}else {
				if (respuesta.equals("Invalido")) {
					JOptionPane.showMessageDialog(null, "El pass no corresponde");
				}else {					
					JOptionPane.showMessageDialog(null,"Bienvenido: " +respuesta);
					miCoordinador.asignarUsurio(respuesta);
					miCoordinador.cerrarVentanaLogin();
				}
			}			
		}
	}

	private void mostrarElementos() {
		// TODO Auto-generated method stub
		String seleccion=(String) comboUsuario.getSelectedItem();
		int index =comboUsuario.getSelectedIndex();
		
		if (index==0) {
			labelPass.setVisible(false);
			campoPass.setVisible(false);
		}else {
			labelPass.setVisible(true);
			campoPass.setVisible(true);				
		}
	}
}
